[package]
name                 = "circus-agent"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
description          = "Build agent for Circus job execution"

[[bin]]
name = "circus-agent"
path = "src/main.rs"

[dependencies]
circus-common.workspace = true
circus-logs.workspace   = true
circus-proto.workspace  = true

async-compression.workspace   = true
capnp.workspace               = true
capnp-futures.workspace       = true
capnp-rpc.workspace           = true
clap.workspace                = true
color-eyre.workspace          = true
config.workspace              = true
futures.workspace             = true
hex.workspace                 = true
libc.workspace                = true
nix.workspace                 = true
parking_lot.workspace         = true
procfs.workspace              = true
reqwest.workspace             = true
rustls.workspace              = true
rustls-native-certs.workspace = true
rustls-pki-types.workspace    = true
serde.workspace               = true
serde_json.workspace          = true
sha2.workspace                = true
tempfile.workspace            = true
thiserror.workspace           = true
tokio.workspace               = true
tokio-rustls.workspace        = true
tokio-util.workspace          = true
tracing.workspace             = true
url.workspace                 = true
uuid.workspace                = true
whoami.workspace              = true

[lints]
workspace = true
