destination = "db/circus-codegen"

[types.mapping."pg_catalog.timestamptz"]
rust-type = "jiff::Timestamp"

[manifest.package]
description  = "Generated PostgreSQL bindings for Circus"
edition      = "2024"
license      = "MPL-2.0"
name         = "circus-codegen"
repository   = "https://github.com/manic-systems/circus"
rust-version = "1.85"
version      = "0.14.0"

[manifest.dependencies]
jiff = { version = "0.2", features = [ "serde" ] }
postgres = { version = "0.19", features = [
  "with-jiff-0_2",
  "with-serde_json-1",
  "with-uuid-1",
], optional = true }
serde_json = { version = "1", features = [ "raw_value" ] }
tokio-postgres = { version = "0.7", features = [ "with-jiff-0_2", "with-serde_json-1", "with-uuid-1" ] }
uuid = { version = "1", features = [ "serde" ] }
