//! Generate the user-facing API route reference from the `OpenAPI` contract.

use std::{fmt::Write, fs};

use color_eyre::{
  Result,
  eyre::{Context, bail},
};
use serde_json::{Map, Value};
use utoipa::openapi::OpenApi;

use crate::openapi_check::{
  display_path,
  method_rank,
  openapi_document,
  openapi_value,
  workspace_root,
};

const GENERATED_HEADER: &str = "<!-- Generated by `cargo run -p circus-xtask \
                                -- api-docs`. Do not edit by hand. -->";

#[derive(Debug, Clone)]
struct DocumentedOperation {
  method:    String,
  path:      String,
  summary:   String,
  responses: String,
}

pub fn run(check: bool) -> Result<()> {
  #![expect(clippy::print_stdout, reason = "xtask CLI output is intentional")]
  let root = workspace_root()?;
  let docs_path = root.join("docs/API.md");
  let generated = generate();

  if check {
    let existing = fs::read_to_string(&docs_path)
      .with_context(|| format!("reading {}", docs_path.display()))?;
    if existing != generated {
      bail!(
        "{} is out of date; run `cargo run -p circus-xtask -- api-docs`",
        docs_path.display()
      );
    }
    println!("API docs are current: {}", docs_path.display());
    return Ok(());
  }

  fs::write(&docs_path, generated)
    .with_context(|| format!("writing {}", docs_path.display()))?;
  println!("Generated {}", docs_path.display());
  Ok(())
}

fn generate() -> String {
  let spec = openapi_document();
  let mut operations = documented_operations(&spec);
  operations.sort_by(|a, b| {
    a.path
      .cmp(&b.path)
      .then(method_rank(&a.method).cmp(&method_rank(&b.method)))
  });

  let mut out = String::new();
  let _ = writeln!(out, "# Circus API\n");
  let _ = writeln!(out, "{GENERATED_HEADER}\n");
  out.push_str(
    "This reference is generated from the server's OpenAPI contract.\n",
  );
  out.push_str(
    "Rebuild it after changing API routes or operation summaries with:\n\n",
  );
  out.push_str("```bash\n");
  out.push_str("cargo run -p circus-xtask -- api-docs\n");
  out.push_str("```\n\n");
  out.push_str(
    "All versioned JSON endpoints live under `/api/v1`. By default, `GET`,\n",
  );
  out.push_str(
    "`HEAD`, and `OPTIONS` requests require an API key or authenticated\n",
  );
  out.push_str(
    "session unless `server.require_api_key_for_reads = false` is \
     configured.\n",
  );
  out.push_str("Mutating requests require\n");
  out.push_str(
    "`Authorization: Bearer <api-key>` or an authenticated browser session \
     and\n",
  );
  out.push_str(
    "may require a specific role. Public compatibility endpoints such as\n",
  );
  out.push_str(
    "webhooks, health, metrics, and cache routes live outside that API key \
     gate.\n\n",
  );
  out.push_str("## Endpoints\n\n");
  out.push_str("<!-- markdownlint-disable MD013 -->\n\n");
  out.push_str("| Method | Endpoint | Description | Responses |\n");
  out.push_str("| ------ | -------- | ----------- | --------- |\n");

  for op in operations {
    let _ = writeln!(
      out,
      "| {} | `{}` | {} | {} |",
      op.method,
      op.path,
      markdown_escape(&op.summary),
      markdown_escape(&op.responses),
    );
  }

  out.push_str("\n<!-- markdownlint-enable MD013 -->\n");
  out
}

fn documented_operations(spec: &OpenApi) -> Vec<DocumentedOperation> {
  let value = openapi_value(spec);
  let Some(paths) = value.get("paths").and_then(Value::as_object) else {
    return Vec::new();
  };

  paths
    .iter()
    .flat_map(|(path, item)| documented_path_operations(&value, path, item))
    .collect()
}

fn documented_path_operations(
  spec: &Value,
  path: &str,
  item: &Value,
) -> Vec<DocumentedOperation> {
  let Some(methods) = item.as_object() else {
    return Vec::new();
  };

  methods
    .iter()
    .filter(|(method, _)| is_http_method(method))
    .map(|(method, operation)| {
      DocumentedOperation {
        method:    method.to_uppercase(),
        path:      display_path(spec, path),
        summary:   operation_summary(operation),
        responses: operation_responses(operation),
      }
    })
    .collect()
}

fn operation_summary(operation: &Value) -> String {
  operation
    .get("summary")
    .or_else(|| operation.get("description"))
    .and_then(Value::as_str)
    .unwrap_or("Documented endpoint")
    .to_string()
}

fn operation_responses(operation: &Value) -> String {
  let responses = operation
    .get("responses")
    .and_then(Value::as_object)
    .map(response_keys)
    .unwrap_or_default();
  if responses.is_empty() {
    "-".to_string()
  } else {
    responses.join(", ")
  }
}

fn response_keys(responses: &Map<String, Value>) -> Vec<String> {
  responses.keys().map(ToString::to_string).collect()
}

fn is_http_method(method: &str) -> bool {
  matches!(
    method,
    "get" | "head" | "options" | "post" | "put" | "patch" | "delete"
  )
}

fn markdown_escape(input: &str) -> String {
  input.replace('|', "\\|").replace('\n', " ")
}

#[cfg(test)]
mod tests {
  #![expect(
    clippy::expect_used,
    reason = "xtask drift tests should fail loudly"
  )]

  use super::*;

  #[test]
  fn generated_api_docs_are_current() {
    let root = workspace_root().expect("workspace root");
    let expected = generate();
    let docs_path = root.join("docs/API.md");
    let actual = fs::read_to_string(&docs_path).expect("read docs/API.md");
    assert_eq!(
      actual, expected,
      "docs/API.md is out of date; run `cargo run -p circus-xtask -- api-docs`"
    );
  }
}
