[package]
name                 = "circus-xtask"
version              = "0.1.0"
edition.workspace    = true
license.workspace    = true
repository.workspace = true
publish              = false

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
circus-server.workspace = true
clap.workspace          = true
color-eyre.workspace    = true
openapiv3.workspace     = true
regex.workspace         = true
serde_json.workspace    = true

[lints]
workspace = true
