[package]
name                 = "circus-common"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
argon2.workspace            = true
base64.workspace            = true
chrono.workspace            = true
circus-config.workspace     = true
circus-logs.workspace       = true
circus-migrations.workspace = true
circus-nix.workspace        = true
circus-types                = { workspace = true, features = [ "sqlx" ] }
clap.workspace              = true
color-eyre.workspace        = true
git2.workspace              = true
hex.workspace               = true
lettre.workspace            = true
libc.workspace              = true
nix.workspace               = true
num_enum.workspace          = true
password-hash.workspace     = true
regex.workspace             = true
reqwest.workspace           = true
ring.workspace              = true
rustls.workspace            = true
serde.workspace             = true
serde_json.workspace        = true
sha2.workspace              = true
shellexpand.workspace       = true
sqlx.workspace              = true
tempfile.workspace          = true
thiserror.workspace         = true
tokio.workspace             = true
tracing.workspace           = true
url.workspace               = true
urlencoding.workspace       = true
uuid.workspace              = true
whoami.workspace            = true

[dev-dependencies]
toml.workspace = true

[lints]
workspace = true
