[package]
name                 = "circus-types"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
description          = "Shared type definitions for Circus"

[features]
clap    = [ "dep:clap" ]
default = [  ]

[dependencies]
clap            = { workspace = true, optional = true }
regex.workspace = true
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
