[package]
name                 = "circus-types"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[features]
clap    = [ "dep:clap" ]
default = [  ]
sqlx    = [ "dep:sqlx" ]

[dependencies]
clap            = { workspace = true, optional = true }
regex.workspace = true
serde.workspace = true
sqlx            = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
