[package]
name                 = "circus-proto"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true
description          = "Cap'n Proto RPC bindings for Circus"

[dependencies]
capnp.workspace         = true
capnp-futures.workspace = true
capnp-rpc.workspace     = true
futures.workspace       = true
serde_json.workspace    = true
thiserror.workspace     = true

[build-dependencies]
capnpc.workspace = true

[lints]
workspace = true
