[package]
name                 = "circus-server"
version.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
askama.workspace                         = true
async-compression.workspace              = true
async-stream.workspace                   = true
axum.workspace                           = true
axum-extra.workspace                     = true
base64.workspace                         = true
chrono.workspace                         = true
circus-proto.workspace                   = true
clap.workspace                           = true
color-eyre.workspace                     = true
config.workspace                         = true
dashmap.workspace                        = true
futures.workspace                        = true
harmonia-file-nar.workspace              = true
harmonia-store-content-address.workspace = true
harmonia-store-nar-info.workspace        = true
harmonia-store-path.workspace            = true
harmonia-store-path-info.workspace       = true
harmonia-utils-hash.workspace            = true
hex.workspace                            = true
hmac.workspace                           = true
ldap3.workspace                          = true
moka.workspace                           = true
oauth2.workspace                         = true
reqwest.workspace                        = true
ring.workspace                           = true
serde.workspace                          = true
serde_json.workspace                     = true
sha2.workspace                           = true
sqlx                                     = { workspace = true, features = [ "sqlite" ] }
subtle.workspace                         = true
tar.workspace                            = true
thiserror.workspace                      = true
tokio.workspace                          = true
tokio-util.workspace                     = true
toml.workspace                           = true
tower.workspace                          = true
tower-http.workspace                     = true
tracing.workspace                        = true
tracing-subscriber.workspace             = true
uuid.workspace                           = true

# Our crates
circus-common.workspace       = true
circus-config.workspace       = true
circus-notification.workspace = true

regex.workspace = true

[dev-dependencies]
serde_urlencoded = "0.7"
tower.workspace  = true

[lints]
workspace = true
