name: Nix

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: cachix/install-nix-action@v31
      - name: Check tree formatting
        run: nix build .#checks.x86_64-linux.formatting -L --no-link

  changes:
    name: Detect Changed Files
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.changed-files.outputs.files }}
    steps:
      - uses: actions/checkout@v6.0.3
      - id: changed-files
        uses: dorny/paths-filter@v4
        with:
          filters: |
            files:
              - '.github/workflows/nix.yml'
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'crates/**'
              - 'nix/**'
              - 'flake.nix'
              - 'flake.lock'

  build-packages:
    name: Build Packages
    needs: changes
    if: ${{ needs.changes.outputs.files_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: extra-experimental-features = nix-command flakes

      - name: Restore and save cached paths
        id: cache-store-restore
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-packages-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock', 'Cargo.lock', 'Cargo.toml', 'crates/**') }}
          restore-prefixes-first-match: nix-packages-${{ runner.os }}-
          gc-max-store-size-linux: 5G
          purge: true
          purge-prefixes: nix-packages-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Build all circus packages
        run: |
          nix build .#circus-cli .#circus-agent .#circus-agent-static \
                    .#circus-evaluator \
                    .#circus-queue-runner .#circus-server -L --no-link

  build:
    name: Build ${{ matrix.package }}
    needs: [changes, build-packages]
    if: ${{ needs.changes.outputs.files_changed == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - circus-cli
          - circus-agent
          - circus-agent-static
          - circus-evaluator
          - circus-queue-runner
          - circus-server
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: cachix/install-nix-action@v31
      - name: Restore cached paths
        id: cache-store-restore
        uses: nix-community/cache-nix-action/restore@v7
        with:
          primary-key: nix-packages-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock', 'Cargo.lock', 'Cargo.toml', 'crates/**') }}
          restore-prefixes-first-match: nix-packages-${{ runner.os }}-

      - name: Build ${{ matrix.package }}
        run: nix build .#${{ matrix.package }} -L --no-link

  nixos-module-agent:
    name: Build NixOS module agent package
    needs: changes
    if: ${{ needs.changes.outputs.files_changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3
      - uses: cachix/install-nix-action@v31
      - name: Restore cached paths
        id: cache-store-restore
        uses: nix-community/cache-nix-action@v7
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock', 'Cargo.lock', 'Cargo.toml', 'crates/**') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 5G
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-last-accessed: 0
          purge-primary-key: never

      - name: Build NixOS module agent package
        run: nix build .#checks.x86_64-linux.nixos-module-agent-package -L --no-link
